// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module vector_adder_machine_regmap (
        input wire clk,
        input wire rst,

        axi4lite_intf.slave s_axil,

        input vector_adder_machine_regmap_pkg::vector_adder_machine_regmap__in_t hwif_in,
        output vector_adder_machine_regmap_pkg::vector_adder_machine_regmap__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [8:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    `ifndef SYNTHESIS
        initial begin
            assert_bad_addr_width: assert($bits(s_axil.ARADDR) >= vector_adder_machine_regmap_pkg::VECTOR_ADDER_MACHINE_REGMAP_MIN_ADDR_WIDTH)
                else $error("Interface address width of %0d is too small. Shall be at least %0d bits", $bits(s_axil.ARADDR), vector_adder_machine_regmap_pkg::VECTOR_ADDER_MACHINE_REGMAP_MIN_ADDR_WIDTH);
            assert_bad_data_width: assert($bits(s_axil.WDATA) == vector_adder_machine_regmap_pkg::VECTOR_ADDER_MACHINE_REGMAP_DATA_WIDTH)
                else $error("Interface data width of %0d is incorrect. Shall be %0d bits", $bits(s_axil.WDATA), vector_adder_machine_regmap_pkg::VECTOR_ADDER_MACHINE_REGMAP_DATA_WIDTH);
        end
    `endif

    // Max Outstanding Transactions: 2
    logic [1:0] axil_n_in_flight;
    logic axil_prev_was_rd;
    logic axil_arvalid;
    logic [8:0] axil_araddr;
    logic axil_ar_accept;
    logic axil_awvalid;
    logic [8:0] axil_awaddr;
    logic axil_wvalid;
    logic [31:0] axil_wdata;
    logic [3:0] axil_wstrb;
    logic axil_aw_accept;
    logic axil_resp_acked;

    // Transaction request acceptance
    always_ff @(posedge clk) begin
        if(rst) begin
            axil_prev_was_rd <= '0;
            axil_arvalid <= '0;
            axil_araddr <= '0;
            axil_awvalid <= '0;
            axil_awaddr <= '0;
            axil_wvalid <= '0;
            axil_wdata <= '0;
            axil_wstrb <= '0;
            axil_n_in_flight <= '0;
        end else begin
            // AR* acceptance register
            if(axil_ar_accept) begin
                axil_prev_was_rd <= '1;
                axil_arvalid <= '0;
            end
            if(s_axil.ARVALID && s_axil.ARREADY) begin
                axil_arvalid <= '1;
                axil_araddr <= s_axil.ARADDR;
            end

            // AW* & W* acceptance registers
            if(axil_aw_accept) begin
                axil_prev_was_rd <= '0;
                axil_awvalid <= '0;
                axil_wvalid <= '0;
            end
            if(s_axil.AWVALID && s_axil.AWREADY) begin
                axil_awvalid <= '1;
                axil_awaddr <= s_axil.AWADDR;
            end
            if(s_axil.WVALID && s_axil.WREADY) begin
                axil_wvalid <= '1;
                axil_wdata <= s_axil.WDATA;
                axil_wstrb <= s_axil.WSTRB;
            end

            // Keep track of in-flight transactions
            if((axil_ar_accept || axil_aw_accept) && !axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight + 1'b1;
            end else if(!(axil_ar_accept || axil_aw_accept) && axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight - 1'b1;
            end
        end
    end

    always_comb begin
        s_axil.ARREADY = (!axil_arvalid || axil_ar_accept);
        s_axil.AWREADY = (!axil_awvalid || axil_aw_accept);
        s_axil.WREADY = (!axil_wvalid || axil_aw_accept);
    end

    // Request dispatch
    always_comb begin
        cpuif_wr_data = axil_wdata;
        for(int i=0; i<4; i++) begin
            cpuif_wr_biten[i*8 +: 8] = {8{axil_wstrb[i]}};
        end
        cpuif_req = '0;
        cpuif_req_is_wr = '0;
        cpuif_addr = '0;
        axil_ar_accept = '0;
        axil_aw_accept = '0;

        if(axil_n_in_flight < 2'd2) begin
            // Can safely issue more transactions without overwhelming response buffer
            if(axil_arvalid && !axil_prev_was_rd) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = {axil_araddr[8:2], 2'b0};
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end else if(axil_awvalid && axil_wvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '1;
                cpuif_addr = {axil_awaddr[8:2], 2'b0};
                if(!cpuif_req_stall_wr) axil_aw_accept = '1;
            end else if(axil_arvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = {axil_araddr[8:2], 2'b0};
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end
        end
    end


    // AXI4-Lite Response Logic
    logic axil_resp_buffer_is_wr[2];
    logic axil_resp_buffer_err[2];
    logic [31:0] axil_resp_buffer_rdata[2];

    logic [1:0] axil_resp_wptr;
    logic [1:0] axil_resp_rptr;

    always_ff @(posedge clk) begin
        if(rst) begin
            for(int i=0; i<2; i++) begin
                axil_resp_buffer_is_wr[i] <= '0;
                axil_resp_buffer_err[i] <= '0;
                axil_resp_buffer_rdata[i] <= '0;
            end
            axil_resp_wptr <= '0;
            axil_resp_rptr <= '0;
        end else begin
            // Store responses in buffer until AXI response channel accepts them
            if(cpuif_rd_ack || cpuif_wr_ack) begin
                if(cpuif_rd_ack) begin
                    axil_resp_buffer_is_wr[axil_resp_wptr[0:0]] <= '0;
                    axil_resp_buffer_err[axil_resp_wptr[0:0]] <= cpuif_rd_err;
                    axil_resp_buffer_rdata[axil_resp_wptr[0:0]] <= cpuif_rd_data;

                end else if(cpuif_wr_ack) begin
                    axil_resp_buffer_is_wr[axil_resp_wptr[0:0]] <= '1;
                    axil_resp_buffer_err[axil_resp_wptr[0:0]] <= cpuif_wr_err;
                end
                axil_resp_wptr <= axil_resp_wptr + 1'b1;
            end

            // Advance read pointer when acknowledged
            if(axil_resp_acked) begin
                axil_resp_rptr <= axil_resp_rptr + 1'b1;
            end
        end
    end

    always_comb begin
        axil_resp_acked = '0;
        s_axil.BVALID = '0;
        s_axil.RVALID = '0;
        if(axil_resp_rptr != axil_resp_wptr) begin
            if(axil_resp_buffer_is_wr[axil_resp_rptr[0:0]]) begin
                s_axil.BVALID = '1;
                if(s_axil.BREADY) axil_resp_acked = '1;
            end else begin
                s_axil.RVALID = '1;
                if(s_axil.RREADY) axil_resp_acked = '1;
            end
        end

        s_axil.RDATA = axil_resp_buffer_rdata[axil_resp_rptr[0:0]];
        if(axil_resp_buffer_err[axil_resp_rptr[0:0]]) begin
            s_axil.BRESP = 2'b10;
            s_axil.RRESP = 2'b10;
        end else begin
            s_axil.BRESP = 2'b00;
            s_axil.RRESP = 2'b00;
        end
    end

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic instruction;
        logic status;
        struct {
            logic elems[4];
        } vectors[8];
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic [8:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        decoded_reg_strb.instruction = cpuif_req_masked & (cpuif_addr == 9'h0);
        decoded_reg_strb.status = cpuif_req_masked & (cpuif_addr == 9'h4);
        for(int i0=0; i0<8; i0++) begin
            for(int i1=0; i1<4; i1++) begin
                decoded_reg_strb.vectors[i0].elems[i1] = cpuif_req_masked & (cpuif_addr == 9'h100 + (9)'(i0) * 9'h10 + (9)'(i1) * 9'h4);
            end
        end
        decoded_err = '0;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } op;
            struct {
                logic [2:0] next;
                logic load_next;
            } rega;
            struct {
                logic [2:0] next;
                logic load_next;
            } regb;
            struct {
                logic [2:0] next;
                logic load_next;
            } dest;
        } instruction;
        struct {
            struct {
                logic next;
                logic load_next;
            } done;
            struct {
                logic next;
                logic load_next;
            } error;
            struct {
                logic next;
                logic load_next;
            } clear;
        } status;
        struct {
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } data;
            } elems[4];
        } vectors[8];
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic [7:0] value;
            } op;
            struct {
                logic [2:0] value;
            } rega;
            struct {
                logic [2:0] value;
            } regb;
            struct {
                logic [2:0] value;
            } dest;
        } instruction;
        struct {
            struct {
                logic value;
            } done;
            struct {
                logic value;
            } error;
            struct {
                logic value;
            } clear;
        } status;
        struct {
            struct {
                struct {
                    logic [31:0] value;
                } data;
            } elems[4];
        } vectors[8];
    } field_storage_t;
    field_storage_t field_storage;

    // Field: vector_adder_machine_regmap.instruction.op
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.instruction.op.value;
        load_next_c = '0;
        if(decoded_reg_strb.instruction && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.instruction.op.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.instruction.op.next = next_c;
        field_combo.instruction.op.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.instruction.op.load_next) begin
            field_storage.instruction.op.value <= field_combo.instruction.op.next;
        end
    end
    assign hwif_out.instruction.op.value = field_storage.instruction.op.value;
    assign hwif_out.instruction.op.swmod = decoded_reg_strb.instruction && decoded_req_is_wr && |(decoded_wr_biten[7:0]);
    // Field: vector_adder_machine_regmap.instruction.rega
    always_comb begin
        automatic logic [2:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.instruction.rega.value;
        load_next_c = '0;
        if(decoded_reg_strb.instruction && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.instruction.rega.value & ~decoded_wr_biten[10:8]) | (decoded_wr_data[10:8] & decoded_wr_biten[10:8]);
            load_next_c = '1;
        end
        field_combo.instruction.rega.next = next_c;
        field_combo.instruction.rega.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.instruction.rega.load_next) begin
            field_storage.instruction.rega.value <= field_combo.instruction.rega.next;
        end
    end
    assign hwif_out.instruction.rega.value = field_storage.instruction.rega.value;
    // Field: vector_adder_machine_regmap.instruction.regb
    always_comb begin
        automatic logic [2:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.instruction.regb.value;
        load_next_c = '0;
        if(decoded_reg_strb.instruction && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.instruction.regb.value & ~decoded_wr_biten[13:11]) | (decoded_wr_data[13:11] & decoded_wr_biten[13:11]);
            load_next_c = '1;
        end
        field_combo.instruction.regb.next = next_c;
        field_combo.instruction.regb.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.instruction.regb.load_next) begin
            field_storage.instruction.regb.value <= field_combo.instruction.regb.next;
        end
    end
    assign hwif_out.instruction.regb.value = field_storage.instruction.regb.value;
    // Field: vector_adder_machine_regmap.instruction.dest
    always_comb begin
        automatic logic [2:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.instruction.dest.value;
        load_next_c = '0;
        if(decoded_reg_strb.instruction && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.instruction.dest.value & ~decoded_wr_biten[16:14]) | (decoded_wr_data[16:14] & decoded_wr_biten[16:14]);
            load_next_c = '1;
        end
        field_combo.instruction.dest.next = next_c;
        field_combo.instruction.dest.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(field_combo.instruction.dest.load_next) begin
            field_storage.instruction.dest.value <= field_combo.instruction.dest.next;
        end
    end
    assign hwif_out.instruction.dest.value = field_storage.instruction.dest.value;
    // Field: vector_adder_machine_regmap.status.done
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.status.done.value;
        load_next_c = '0;
        if(hwif_in.status.done.we) begin // HW Write - we
            next_c = hwif_in.status.done.next;
            load_next_c = '1;
        end
        field_combo.status.done.next = next_c;
        field_combo.status.done.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.status.done.value <= 1'h0;
        end else begin
            if(field_combo.status.done.load_next) begin
                field_storage.status.done.value <= field_combo.status.done.next;
            end
        end
    end
    // Field: vector_adder_machine_regmap.status.error
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.status.error.value;
        load_next_c = '0;
        if(hwif_in.status.error.we) begin // HW Write - we
            next_c = hwif_in.status.error.next;
            load_next_c = '1;
        end
        field_combo.status.error.next = next_c;
        field_combo.status.error.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.status.error.value <= 1'h0;
        end else begin
            if(field_combo.status.error.load_next) begin
                field_storage.status.error.value <= field_combo.status.error.next;
            end
        end
    end
    // Field: vector_adder_machine_regmap.status.clear
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.status.clear.value;
        load_next_c = '0;
        if(decoded_reg_strb.status && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.status.clear.value & ~decoded_wr_biten[2:2]) | (decoded_wr_data[2:2] & decoded_wr_biten[2:2]);
            load_next_c = '1;
        end else if(hwif_in.status.clear.we) begin // HW Write - we
            next_c = hwif_in.status.clear.next;
            load_next_c = '1;
        end
        field_combo.status.clear.next = next_c;
        field_combo.status.clear.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.status.clear.value <= 1'h0;
        end else begin
            if(field_combo.status.clear.load_next) begin
                field_storage.status.clear.value <= field_combo.status.clear.next;
            end
        end
    end
    assign hwif_out.status.clear.value = field_storage.status.clear.value;
    for(genvar i0=0; i0<8; i0++) begin
        for(genvar i1=0; i1<4; i1++) begin
            // Field: vector_adder_machine_regmap.vectors[].elems[].data
            always_comb begin
                automatic logic [31:0] next_c;
                automatic logic load_next_c;
                next_c = field_storage.vectors[i0].elems[i1].data.value;
                load_next_c = '0;
                if(decoded_reg_strb.vectors[i0].elems[i1] && decoded_req_is_wr) begin // SW write
                    next_c = (field_storage.vectors[i0].elems[i1].data.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                    load_next_c = '1;
                end else if(hwif_in.vectors[i0].elems[i1].data.we) begin // HW Write - we
                    next_c = hwif_in.vectors[i0].elems[i1].data.next;
                    load_next_c = '1;
                end
                field_combo.vectors[i0].elems[i1].data.next = next_c;
                field_combo.vectors[i0].elems[i1].data.load_next = load_next_c;
            end
            always_ff @(posedge clk) begin
                if(field_combo.vectors[i0].elems[i1].data.load_next) begin
                    field_storage.vectors[i0].elems[i1].data.value <= field_combo.vectors[i0].elems[i1].data.next;
                end
            end
            assign hwif_out.vectors[i0].elems[i1].data.value = field_storage.vectors[i0].elems[i1].data.value;
        end
    end

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic [8:0] rd_mux_addr;
    assign rd_mux_addr = decoded_addr;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_data_var = '0;
        if(rd_mux_addr == 9'h0) begin
            readback_data_var[7:0] = field_storage.instruction.op.value;
            readback_data_var[10:8] = field_storage.instruction.rega.value;
            readback_data_var[13:11] = field_storage.instruction.regb.value;
            readback_data_var[16:14] = field_storage.instruction.dest.value;
        end
        if(rd_mux_addr == 9'h4) begin
            readback_data_var[0] = field_storage.status.done.value;
            readback_data_var[1] = field_storage.status.error.value;
            readback_data_var[2] = field_storage.status.clear.value;
        end
        for(int i0=0; i0<8; i0++) begin
            for(int i1=0; i1<4; i1++) begin
                if(rd_mux_addr == 9'h100 + (9)'(i0) * 9'h10 + (9)'(i1) * 9'h4) begin
                    readback_data_var[31:0] = field_storage.vectors[i0].elems[i1].data.value;
                end
            end
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
