// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package vector_adder_machine_regmap_pkg;

    localparam VECTOR_ADDER_MACHINE_REGMAP_DATA_WIDTH = 32;
    localparam VECTOR_ADDER_MACHINE_REGMAP_MIN_ADDR_WIDTH = 9;
    localparam VECTOR_ADDER_MACHINE_REGMAP_SIZE = 'h180;

    typedef struct {
        logic next;
        logic we;
    } vector_adder_machine_regmap__status_reg__done__in_t;

    typedef struct {
        logic next;
        logic we;
    } vector_adder_machine_regmap__status_reg__error__in_t;

    typedef struct {
        logic next;
        logic we;
    } vector_adder_machine_regmap__status_reg__clear__in_t;

    typedef struct {
        vector_adder_machine_regmap__status_reg__done__in_t done;
        vector_adder_machine_regmap__status_reg__error__in_t error;
        vector_adder_machine_regmap__status_reg__clear__in_t clear;
    } vector_adder_machine_regmap__status_reg__in_t;

    typedef struct {
        logic [31:0] next;
        logic we;
    } vector_adder_machine_regmap__vector_element_t__data__in_t;

    typedef struct {
        vector_adder_machine_regmap__vector_element_t__data__in_t data;
    } vector_adder_machine_regmap__vector_element_t__in_t;

    typedef struct {
        vector_adder_machine_regmap__vector_element_t__in_t elems[4];
    } vector_adder_machine_regmap__vector_reg_t__in_t;

    typedef struct {
        vector_adder_machine_regmap__status_reg__in_t status;
        vector_adder_machine_regmap__vector_reg_t__in_t vectors[8];
    } vector_adder_machine_regmap__in_t;

    typedef struct {
        logic [7:0] value;
        logic swmod;
    } vector_adder_machine_regmap__instruction__op__out_t;

    typedef struct {
        logic [2:0] value;
    } vector_adder_machine_regmap__instruction__rega__out_t;

    typedef struct {
        logic [2:0] value;
    } vector_adder_machine_regmap__instruction__regb__out_t;

    typedef struct {
        logic [2:0] value;
    } vector_adder_machine_regmap__instruction__dest__out_t;

    typedef struct {
        vector_adder_machine_regmap__instruction__op__out_t op;
        vector_adder_machine_regmap__instruction__rega__out_t rega;
        vector_adder_machine_regmap__instruction__regb__out_t regb;
        vector_adder_machine_regmap__instruction__dest__out_t dest;
    } vector_adder_machine_regmap__instruction__out_t;

    typedef struct {
        logic value;
    } vector_adder_machine_regmap__status_reg__clear__out_t;

    typedef struct {
        vector_adder_machine_regmap__status_reg__clear__out_t clear;
    } vector_adder_machine_regmap__status_reg__out_t;

    typedef struct {
        logic [31:0] value;
    } vector_adder_machine_regmap__vector_element_t__data__out_t;

    typedef struct {
        vector_adder_machine_regmap__vector_element_t__data__out_t data;
    } vector_adder_machine_regmap__vector_element_t__out_t;

    typedef struct {
        vector_adder_machine_regmap__vector_element_t__out_t elems[4];
    } vector_adder_machine_regmap__vector_reg_t__out_t;

    typedef struct {
        vector_adder_machine_regmap__instruction__out_t instruction;
        vector_adder_machine_regmap__status_reg__out_t status;
        vector_adder_machine_regmap__vector_reg_t__out_t vectors[8];
    } vector_adder_machine_regmap__out_t;
endpackage
